version: "3.8"

name: markdown-notes

services:
  backend:
    container_name: "markdown-notes-backend"
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: "markdown-notes-db"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    container_name: "markdown-notes-db-test"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-test-data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
